{
    "description": "Test that passwordless signUp with an existing username fails",
    "preConditions": {
        "amplify-configuration": "authconfiguration_userauth.json",
        "state": "SignedOut_Configured.json",
        "mockedResponses": [
            {
                "type": "cognitoIdentityProvider",
                "apiName": "signUp",
                "responseType": "failure",
                "response": {
                    "errorType": "UsernameExistsException",
                    "errorMessage": "Error type: Client, Protocol response: (empty response)"
                }
            }
        ]
    },
    "api": {
        "name": "signUp",
        "params": {
            "username": "anExistingUsername",
            "password": ""
        },
        "options": {
            "userAttributes": {
                "email": "user@domain.com"
            }
        }
    },
    "validations": [
        {
            "type": "cognitoIdentityProvider",
            "apiName": "signUp",
            "request": {
                "clientId": "testAppClientId",
                "username": "anExistingUsername",
                "password": "",
                "userAttributes": [
                    {
                        "name": "email",
                        "value": "user@domain.com"
                    }
                ]
            }
        },
        {
            "type": "amplify",
            "apiName": "signUp",
            "responseType": "failure",
            "response": {
                "errorType": "UsernameExistsException",
                "errorMessage": "Username already exists in the system.",
                "recoverySuggestion": "Retry operation and enter another username.",
                "cause": {
                    "errorType": "UsernameExistsException",
                    "errorMessage": "Error type: Client, Protocol response: (empty response)"
                }
            }
        }
    ]
}